# Generated by Django 5.2.4 on 2025-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='abhay', max_length=100),
            preserve_default=False,
        ),
    ]
